namespace: 'patchone'
name: 'collection'
version: '1.0.0'
readme: 'README.md'
authors:
  - 'Simon Bärlocher (https://sbaerlocher.ch)'
  - 'ITIGO AG (https://itigo.ch)'
description: 'Collection of Virtualization Software for Linux: VirtualBox, KVM, VMware, Docker-CE, Podman'
license:
  - 'MIT'
tags:
  - linux
  - windows
  - update
  - apt
  - yum
  - collection
repository: 'https://www.github.com/crivetimihai/ansible_virtualization'
homepage: 'https://www.github.com/crivetimihai/ansible_virtualization'
documentation: 'https://crivetimihai.github.io/ansible_virtualization/'
issues: 'https://www.github.com/crivetimihai/ansible_virtualization/issues'
