---
# tasks file for test.test

- name: 'availability updates windows'
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: searched
  register: register_windows_updates

- set_fact:
    windows_package: "{{ register_windows_updates | json_query('filtered_updates.[*][0]') | map(attribute='title') | list }}"

- name: 'availability updates chocolatey'
  win_choco_update_info:
  register: register_update
